### ISSUE TITLE
fizzbuzz 구현

### ISSUE THREAD

**Issue by SeonHongPark** [SeonHongPark/fizzbuzz-for-me#1]
## 목표

나 혼자 완성해보는 fizzbuzz

## 요구사항

- 범위 1~20까지의 정수

## Tasks

- [x] Print 'fizz' if is times of 3
- [x] Print 'Buzz' fi is times of 5
- [x] Print 'fizzbuzz' if is times of 15
- [x] Print i itself for any other cases

# Reference

- https://en.wikipedia.org/wiki/Fizz_buzz
